### ISSUE TITLE
RuntimeError: The session is unavailable because no secret key was set.

### ISSUE THREAD

**Issue by Calibanda** [DinRigtigeFar/yt-interval#1]
In line 12 of the app.py, `os.environ.get("SECRET_KEY")` return `none` for me. Flask hasn't a key and the program returned this exception:
`RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.`
I just set `app.secret_key` with a personal string and the app run.

**Comment by DinRigtigeFar** [comment]
That is the expected behavior. You should have export SECRET_KEY=“somesecretstring” in your .bashrc in ~/.bashrc (or whatever shell you’re using).
If you just run it locally I guess you could put a string (any) directly in the app.py file.

Let me know if it works (or don’t).
Or if it’s difficult to understand what I wrote.

/Christian

**Comment by Calibanda** [comment]
I don't really know how to do this in Windows but I simply edited the source code with a random string so, yeah, the app is working

**Comment by hyber-code** [comment]
Can you please explain how to make it work in windows, how should i set secret key in windows.
```
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
127.0.0.1 - - [20/Nov/2020 10:57:19] "[35m[1mPOST /downloading HTTP/1.1[0m" 500 -
```

**Comment by DinRigtigeFar** [comment]
In windows you can follow this [guide](https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0) on how to set environment variables.

**Comment by DinRigtigeFar** [comment]
Follow the guide here:

https://docs.oracle.com/en/database/oracle/r-enterprise/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0

Mvh.
Christian Jørgensen
