### ISSUE TITLE
Download didn't work: 'ffmpeg' has no attribute 'input'

### ISSUE THREAD

**Issue by LxCasino** [DinRigtigeFar/yt-interval#2]
After I click parse text it says:
`'Done parsing your input. To download click the button.'`

Then I go on `'Redirect to the funhouse (may take some time since I have to download all of your videoes!)'`

`'Press here to download the media. Might not be ready, just wait then.'`

But at this point, it says the following in the command line:
```
127.0.0.1 - - [11/Mar/2020 19:35:00] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2020 19:36:15] "POST /downloading HTTP/1.1" 200 -
I couldn't download ('https://www.youtube.com/watch?xxxxxxxxxx', ['00:02:44', '00:00:21']) due to: module 'ffmpeg' has no attribute 'input'
127.0.0.1 - - [11/Mar/2020 19:36:35] "POST /waiting HTTP/1.1" 200 -
127.0.0.1 - - [11/Mar/2020 19:36:42] "GET /waiting/done HTTP/1.1" 200 -
```

I've never altered any ffmpeg settings.

And the media.zip which I downloaded has nothing in it. I can not extract anything.

**Comment by DinRigtigeFar** [comment]
The empty media.zip file is due to the program not being able to download the video.
And the video can't be downloaded due to an ffmpeg error.
What's you ffmpeg version? It should be printed in the terminal when starting the download.
`ffmpeg version 4.2.2` is the version I currently have.

That being said, I tried to download the video you emailed me and I got a stream error (from ffmpeg). A solution could be to try and loop over all the video streams and see if one of them works. I'll have to think about that since if it isn't going to work then I can't fix the problem.

**Comment by DinRigtigeFar** [comment]
Apparently the error I got was due to my VPN. When I terminated it the video downloaded just fine. That's a thing I havn't seen before and must be due to YouTube geo restrictions.

**Comment by LxCasino** [comment]
Interesting. I have a VPN aswell and will try to download it again with the VPN not being active.

**Comment by LxCasino** [comment]
> The empty media.zip file is due to the program not being able to download the video.
> And the video can't be downloaded due to an ffmpeg error.
> What's you ffmpeg version? It should be printed in the terminal when starting the download.
> `ffmpeg version 4.2.2` is the version I currently have.
 
I got the same version. 
It says in the error message from the console:
> due to: module 'ffmpeg' has no attribute 'input'

How do I set an 'input'? Maybe this helps?


> Interesting. I have a VPN aswell and will try to download it again with the VPN not being active.

Turning the VPN off didn't help in my case.

**Comment by DinRigtigeFar** [comment]
The issue is referenced [here](https://github.com/kkroening/ffmpeg-python/issues/174).
Try:
```
pip uninstall ffmpeg
pip uninstall ffmpeg-python
pip install ffmpeg-python
```

**Comment by LxCasino** [comment]
> The issue is referenced [here](https://github.com/kkroening/ffmpeg-python/issues/174).
> Try:
> 
> ```
> pip uninstall ffmpeg
> pip uninstall ffmpeg-python
> pip install ffmpeg-python
> ```

Output on the command line looks healthy now, 0 errors.
I have the .mp4 in my yt-interval/tmp folder. 
It's working!

But in the end I get asked if I want to download a media.zip (22 bytes) which is empty.

**Comment by DinRigtigeFar** [comment]
> I have the .mp4 in my yt-interval/tmp folder.

Have you tried opening the video in the above folder?
For some reason it's not collected properly and put in the media.zip folder.

How did you install all the packages. Plain `pip install -r requirements.txt` or into a virtual environment?
If it's the first, then it might be due to some package conflicts and then you should try to create a virtual environment.

**Comment by LxCasino** [comment]
> > I have the .mp4 in my yt-interval/tmp folder.
> 
> Have you tried opening the video in the above folder?
> For some reason it's not collected properly and put in the media.zip folder.

yes I opened it, I can play it via VLC just fine.

> How did you install all the packages. Plain `pip install -r requirements.txt` or into a virtual environment?
> If it's the first, then it might be due to some package conflicts and then you should try to create a virtual environment.

I'm using a virtual env, flask to be precise.

**Comment by DinRigtigeFar** [comment]
So you created it using:
```
cd yt-interval
python3 -m venv flask
```
And activated it:
`. venv/bin/activate`
Or on windows:
```
cd yt-interval
py -3 -m venv flask
```
And activated it:
`venv\Scripts\activate`

And then you installed all of the packages:
`pip install -r requirements.txt`

If you did all of this, then I have no clue as to why you don't get any content into your `media.zip` folder.
Maybe try to delete it before downloading a new file (it's automatically deleted when you press the go back to front page button after downloading).

**Comment by LxCasino** [comment]
I'm on manjaro and I usually start it up like this: 

(being in the yt-interval-folder)
> virtualenv flask
> cd flask
> source bin/activate
> cd ..
> python app.py

> And then you installed all of the packages:
pip install -r requirements.txt

I did not do that. Can you tell me what this does?

**Comment by DinRigtigeFar** [comment]
> pip install -r requirements.txt

Installs all the packages that my program needs. If that's not done then there might be conflicts.

**Comment by LxCasino** [comment]
> > pip install -r requirements.txt
> 
> Installs all the packages that my program needs. If that's not done then there might be conflicts.

oh ok, f*** me right? Doing it right now.

**Comment by LxCasino** [comment]
It's working fine now. A lot of beginner mistakes on my part.
Thanks a lot!
