### ISSUE TITLE
empty media.zip

### ISSUE THREAD

**Issue by enchilada-composer** [DinRigtigeFar/yt-interval#3]
hello,
is this still working?
I did like you told me to do but all I get is an empty media.zip.
Did I miss something? I set the secret key, it gets me to the front end of your app, but I never get the interval I want.

//Should propably tell you that I am on Linux.

**Comment by DinRigtigeFar** [comment]
I don’t know. Haven’t tested it in a while. Can check tomorrow maybe.

Regards
Christian

**Comment by DinRigtigeFar** [comment]
> hello,
> is this still working?
> I did like you told me to do but all I get is an empty media.zip.
> Did I miss something? I set the secret key, it gets me to the front end of your app, but I never get the interval I want.
> 
> //Should propably tell you that I am on Linux.

I am so sorry I've taken this long to respond properly, but life's gotten in the way.

I've just tested it using this [link](https://www.youtube.com/watch?v=YQhJm3QkXq0) and it worked fine. If you click the download button before the video has been processed then the folder will be empty (I'm working on not redirecting before it's all done).

Let me know if it works.
