### ISSUE TITLE
can't seem to get it to work

### ISSUE THREAD

**Issue by unculcated** [DinRigtigeFar/yt-interval#4]
Did the installation. Restarted terminal. Nothing.It just downloads the whole yt vid

**Comment by DinRigtigeFar** [comment]
Did you open up your webbrowser and typed in the IP of the program?

**Comment by DinRigtigeFar** [comment]
Sorry for the long reply time.
Can you upload a screenshot of your input to the different screens you go through before pressing download?
That will help me identify the problem.
