### ISSUE TITLE
Missing folder

### ISSUE THREAD

**Issue by hyber-code** [DinRigtigeFar/yt-interval#5]
First of all thank you for the script.

pardon for stupid questions , I am facing two issues.

1. When i reach following step from installation guide, 
``` . venv_yt/bin/activate ```
it justs throws an error is it continuation of the previous step ? or windows issue may be, because ```.``` is not any command.
```
D:\scripts\yt-interval>. venv_yt/bin/activate
'.' is not recognized as an internal or external command,
operable program or batch file.
```

2. after running the last command ``` python yt-interval.py```  from installation guide and opening the server link ``` http://127.0.0.1:5000/ ```, what is the next step ?, because after i run the last command and open the link it throws an error, i am pasting the whole process below. new to flask, couldn't understand how to make it work.
```
D:\scripts\yt-interval>python yt-interval.py
 * Serving Flask app "yt-interval" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
[2020-11-20 10:06:23,390] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\XX\scoop\apps\python\current\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\XX\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\XX\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\XX\scoop\apps\python\current\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\XX\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\XX\scoop\apps\python\current\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\scripts\yt-interval\yt-interval.py", line 17, in index
    if len(os.listdir("./content")) > 0:
FileNotFoundError: [WinError 3] The system cannot find the path specified: './content'
127.0.0.1 - - [20/Nov/2020 10:06:23] "[35m[1mGET / HTTP/1.1[0m" 500 -
```

**Comment by DinRigtigeFar** [comment]
I'm glad you find it useful.
Apparently there's a difference between Mac and Windows when activating a virtual environment. For windows it's one of the two depending on if you use cmd prompt or powershell:

Windows
- cmd.exe: C:\> <venv>\Scripts\activate.bat
- PowerShell: PS C:\> <venv>\Scripts\Activate.ps1

As for the second error that's entirely on me. I have neglected to upload the "content" folder as part of the repository. I'll do so later, but for now you can simply create it in the same folder as the scripts.

Let me know how it works out for you 👍🏻

**Comment by hyber-code** [comment]
thanks for your response, let me create the folder, i will close the issue after testing

**Comment by hyber-code** [comment]
it worked, thank you

**Comment by DinRigtigeFar** [comment]
I have fixed the "bug" by adding the folder.
